// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0lN9o9H7WB2awV-jYCRaqxULaEoFwy-A',
    appId: '1:104741833617:web:3e43a412ab4007387ca830',
    messagingSenderId: '104741833617',
    projectId: 'base-flutter-f5463',
    authDomain: 'base-flutter-f5463.firebaseapp.com',
    storageBucket: 'base-flutter-f5463.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhM8whqU3YRaRnZqEQG1OcLTxGUuZ3Zcc',
    appId: '1:104741833617:android:1fab19f9e72c0d6c7ca830',
    messagingSenderId: '104741833617',
    projectId: 'base-flutter-f5463',
    storageBucket: 'base-flutter-f5463.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSRXYR6XimIkXwqtE9lKdMl_5f4J9wNWI',
    appId: '1:104741833617:ios:d83c859ab921a9eb7ca830',
    messagingSenderId: '104741833617',
    projectId: 'base-flutter-f5463',
    storageBucket: 'base-flutter-f5463.appspot.com',
    iosBundleId: 'com.example.appWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSRXYR6XimIkXwqtE9lKdMl_5f4J9wNWI',
    appId: '1:104741833617:ios:d83c859ab921a9eb7ca830',
    messagingSenderId: '104741833617',
    projectId: 'base-flutter-f5463',
    storageBucket: 'base-flutter-f5463.appspot.com',
    iosBundleId: 'com.example.appWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0lN9o9H7WB2awV-jYCRaqxULaEoFwy-A',
    appId: '1:104741833617:web:48405b292654579a7ca830',
    messagingSenderId: '104741833617',
    projectId: 'base-flutter-f5463',
    authDomain: 'base-flutter-f5463.firebaseapp.com',
    storageBucket: 'base-flutter-f5463.appspot.com',
  );
}
